export { default as backArrow } from './backArrow.svg'
export { default as dog } from './dog.svg'
export { default as menu } from './menu.svg'
export { default as pills } from './pills.svg'
export { default as plus } from './plus.svg'
export { default as seringe } from './seringe.svg'
export { default as gearOption } from './gearOption.svg'
